// <auto-generated />
using System;
using BukenTrainerPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BukenTrainerPortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250401213745_add-check-in-fields")]
    partial class addcheckinfields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BukenTrainerPortal.Models.Athlete", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CoachId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("CoachId");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("BukenTrainerPortal.Models.CheckIn", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("ActivityAdherence")
                        .HasColumnType("integer");

                    b.Property<string>("AffectedMuscleOrSession")
                        .HasColumnType("text");

                    b.Property<int>("AthleteId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AverageWeight")
                        .HasColumnType("numeric");

                    b.Property<int>("CoachId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("DiastolicBloodPressure")
                        .HasColumnType("smallint");

                    b.Property<int?>("DietAdherence")
                        .HasColumnType("integer");

                    b.Property<int?>("EnergyLevel")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FastingGlucoseLevels")
                        .HasColumnType("numeric");

                    b.Property<int?>("HungerLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("MenstrualCyclePhase")
                        .HasColumnType("integer");

                    b.Property<int?>("MuscleRecovery")
                        .HasColumnType("integer");

                    b.Property<string>("NextWeekChallenges")
                        .HasColumnType("text");

                    b.Property<string>("OffPlanMeals")
                        .HasColumnType("text");

                    b.Property<string>("OtherInformation")
                        .HasColumnType("text");

                    b.Property<string>("PlansToAddressChalllenges")
                        .HasColumnType("text");

                    b.Property<string>("ProgressPictureURLs")
                        .HasColumnType("text");

                    b.Property<int?>("SleepQuality")
                        .HasColumnType("integer");

                    b.Property<int?>("StressLevel")
                        .HasColumnType("integer");

                    b.Property<short?>("SystolicBloodPressure")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeeklyAchievements")
                        .HasColumnType("text");

                    b.Property<string>("WeeklyChallenges")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("AthleteId");

                    b.HasIndex("CoachId");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("BukenTrainerPortal.Models.Coach", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("BukenTrainerPortal.Models.Athlete", b =>
                {
                    b.HasOne("BukenTrainerPortal.Models.Coach", "Coach")
                        .WithMany("Athletes")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("BukenTrainerPortal.Models.CheckIn", b =>
                {
                    b.HasOne("BukenTrainerPortal.Models.Athlete", "Athlete")
                        .WithMany("CheckIns")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BukenTrainerPortal.Models.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("BukenTrainerPortal.Models.Athlete", b =>
                {
                    b.Navigation("CheckIns");
                });

            modelBuilder.Entity("BukenTrainerPortal.Models.Coach", b =>
                {
                    b.Navigation("Athletes");
                });
#pragma warning restore 612, 618
        }
    }
}
